name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '.github/**'
      - 'readme.md'
  workflow_dispatch:
  repository_dispatch:
    types: [docker-publish]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine the Docker tag
        id: get_tag
        run: |
          echo "::set-output name=image::ghcr.io/${{ github.repository }}"
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "tag=${{ github.sha }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build Container image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ steps.get_tag.outputs.image }}
          tags: ${{ steps.get_tag.outputs.tag }}
          containerfiles: ./dockerfile

      - name: Push image to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.get_tag.outputs.image }}
          tags: ${{ steps.get_tag.outputs.tag }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

